name: Playwright Python Automation

# ---------------------------------------------------
# Trigger workflow
# ---------------------------------------------------

on:

  # Run on push to main branch
  push:
    branches:
      - main

  # Run on pull request
  pull_request:
    branches:
      - main

  # Manual trigger from GitHub Actions UI
  workflow_dispatch:

# ---------------------------------------------------
# Jobs
# ---------------------------------------------------

jobs:

  playwright-python-tests:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      # Run test on multiple browsers
      matrix:
          # If we cross browser testing mention as list format
        browser: [chromium]

    steps:

      # -------------------------------------------------
      # Checkout repository code
      # -------------------------------------------------

      - name: Checkout Repository
        uses: actions/checkout@v4

      # -------------------------------------------------
      # Setup Python
      # -------------------------------------------------

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # -------------------------------------------------
      # Cache pip dependencies
      # -------------------------------------------------

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # -------------------------------------------------
      # Install dependencies
      # -------------------------------------------------

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # -------------------------------------------------
      # Install Playwright Browsers
      # -------------------------------------------------

      - name: Install Playwright Browsers
        run: |
          playwright install --with-deps

      # -------------------------------------------------
      # Run Playwright Tests
      # -------------------------------------------------

      - name: Run Playwright Tests
        run: |
          pytest
            --html=report-${{ matrix.browser }}.html

      # -------------------------------------------------
      # Upload reports if failed
      # -------------------------------------------------

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.browser }}
          path: |
            report-${{ matrix.browser }}.html
            test-results/
            *.png